server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost/spring_kotlin
    username: root

  jackson:
    serialization: true

  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

security:
  basic:
    enabled: false
  user:
    name: user
    password: 123